# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.
options:
  web_external_url:
    description: |
      The URL under which Loki is externally reachable (for example,
      if Loki is served via a reverse proxy).
      Used for generating relative and absolute links back to
      Loki itself. If the URL has a path portion, it will be used to
      prefix all HTTP endpoints served by Loki.

      This configuration option takes precedence over the URL provided over
      the "ingress" relation.
    type: string
    default: ""
